display_information:
  name: Geppetto-dev
  description: Advanced Slack bot integrating OpenAI's ChatGPT and DALL-E for interactive AI conversations and image generation.
  background_color: "#262729"
features:
  app_home:
    home_tab_enabled: false
    messages_tab_enabled: true
    messages_tab_read_only_enabled: false
  bot_user:
    display_name: Geppetto-dev
    always_online: true
oauth_config:
  scopes:
    bot:
      - app_mentions:read
      - channels:history
      - channels:read
      - chat:write
      - chat:write.public
      - files:write
      - groups:history
      - groups:write
      - im:history
      - im:read
      - im:write
      - mpim:write
      - files:read
settings:
  event_subscriptions:
    bot_events:
      - app_mention
      - message.im
  interactivity:
    is_enabled: true
  org_deploy_enabled: false
  socket_mode_enabled: true
  token_rotation_enabled: false
