name: Build and Test Docker

on:
  push:
    branches: [ "staging" ]

env:
  IMAGE: geppetto

jobs:
  build-and-test:
    name: Setup, Build, and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build Docker Image
      run: |
        docker build \
          --tag ${{ env.IMAGE }}:${{ github.sha }} \
          --build-arg GITHUB_SHA="${{ github.sha }}" \
          --build-arg GITHUB_REF="${{ github.ref }}" \
          

    - name: Run Docker Container
      run: |
        docker run --name ${{ env.IMAGE }}-container -d -p 8080:8080 ${{ env.IMAGE }}:${{ github.sha }}

    - name: Wait for Container Start
      run: sleep 10

    - name: Test Application
      run: curl --fail http://localhost:8080

    - name: Stop and Remove Docker Container
      run: |
        docker stop ${{ env.IMAGE }}-container
        docker rm ${{ env.IMAGE }}-container
