
name: Execute Geppetto Tests

on:
  push:
    branches:
      - main
      - develop

jobs:
  Test-Python3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
     
      - name: Run Python
        run: python --version
      - name: install requirements
        run: |
          pip install -r requirements.txt
          
      - name: Run Test 
        run: |
          python -m xmlrunner discover tests -v -o test_reports
          
      - name: Publish Test Results
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          report_paths: 'test_reports/*.xml'
          detailed_summary: true
