
name: Test Geppetto

on:
  push:

jobs:
  Test-Python3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
     
      - name: Run Python
        run: python --version
      - name: install requirements
        run: pip install -r requirements.txt
        
      - name: Run Test OpenAI y Slack
        run: | 
          python ./tests/test_open_ai.py
          python ./tests/test_slack.py
